/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazGrafica;

import com.mycompany.registro_usuario.Administrativo;
import com.mycompany.registro_usuario.Estudiante;
import com.mycompany.registro_usuario.Profesor;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class interfazRegistro extends javax.swing.JFrame {

    /**
     * Creates new form interfazRegistro
     */
    public interfazRegistro() {
        initComponents();
        ocultarPaneles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        nombreEst = new javax.swing.JTextField();
        edadEst = new javax.swing.JTextField();
        direccionEst = new javax.swing.JTextField();
        telefonoEst = new javax.swing.JTextField();
        facultadEst = new javax.swing.JTextField();
        carreraEst = new javax.swing.JTextField();
        semestreEst = new javax.swing.JTextField();
        apellidoEst = new javax.swing.JTextField();
        emailEst = new javax.swing.JTextField();
        registroEstudiante = new javax.swing.JButton();
        sexoEst = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        nombreProf = new javax.swing.JTextField();
        edadProf = new javax.swing.JTextField();
        direccionProf = new javax.swing.JTextField();
        telefonoProf = new javax.swing.JTextField();
        emailProf = new javax.swing.JTextField();
        contratoProf = new javax.swing.JTextField();
        profesionProf = new javax.swing.JTextField();
        apellidoProf = new javax.swing.JTextField();
        registroProfesores = new javax.swing.JButton();
        sexoProf = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        nombreAdm = new javax.swing.JTextField();
        apellidoAdm = new javax.swing.JTextField();
        edadAdm = new javax.swing.JTextField();
        telefonoAdm = new javax.swing.JTextField();
        emailAdm = new javax.swing.JTextField();
        cargoAdm = new javax.swing.JTextField();
        departamentoAdm = new javax.swing.JTextField();
        registroAdministrativo = new javax.swing.JButton();
        sexoAdm = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("REGISTRO USUARIO");
        jLabel1.setToolTipText("");

        jComboBox1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTUDIANTE", "PROFESOR", "ADMINISTRATIVO" }));
        jComboBox1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                ESTUDIANTE(evt);
                PROFESOR(evt);
                ADMINISTRATIVO(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO ESTUDIANTE ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        nombreEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        nombreEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEstActionPerformed(evt);
            }
        });

        edadEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        edadEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadEstActionPerformed(evt);
            }
        });

        direccionEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        direccionEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionEstActionPerformed(evt);
            }
        });

        telefonoEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        telefonoEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoEstActionPerformed(evt);
            }
        });

        facultadEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Facultad:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        facultadEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facultadEstActionPerformed(evt);
            }
        });

        carreraEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrera:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        carreraEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreraEstActionPerformed(evt);
            }
        });

        semestreEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Semestre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        semestreEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semestreEstActionPerformed(evt);
            }
        });

        apellidoEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        apellidoEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoEstActionPerformed(evt);
            }
        });

        emailEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        emailEst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailEstActionPerformed(evt);
            }
        });

        registroEstudiante.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        registroEstudiante.setText("REGISTRARSE");
        registroEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroEstudianteActionPerformed(evt);
            }
        });

        sexoEst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        sexoEst.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(direccionEst, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(semestreEst, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nombreEst, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoEst, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(telefonoEst, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailEst, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(registroEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(sexoEst, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(edadEst, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(facultadEst, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carreraEst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(facultadEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edadEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carreraEst)
                    .addComponent(sexoEst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(semestreEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registroEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nombreEst.getAccessibleContext().setAccessibleParent(nombreEst);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO PROFESORES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        nombreProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        nombreProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProfActionPerformed(evt);
            }
        });

        edadProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        edadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadProfActionPerformed(evt);
            }
        });

        direccionProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dirección:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        direccionProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionProfActionPerformed(evt);
            }
        });

        telefonoProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        telefonoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoProfActionPerformed(evt);
            }
        });

        emailProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        emailProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailProfActionPerformed(evt);
            }
        });

        contratoProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Contrato:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        contratoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoProfActionPerformed(evt);
            }
        });

        profesionProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profesión:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        profesionProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesionProfActionPerformed(evt);
            }
        });

        apellidoProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        apellidoProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoProfActionPerformed(evt);
            }
        });

        registroProfesores.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        registroProfesores.setText("REGISTRARSE");
        registroProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroProfesoresActionPerformed(evt);
            }
        });

        sexoProf.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        sexoProf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        sexoProf.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(edadProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(contratoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sexoProf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(profesionProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(nombreProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellidoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(telefonoProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(emailProf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(registroProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contratoProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profesionProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoProf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(direccionProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registroProfesores, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO ADMINISTRATIVO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        nombreAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        nombreAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreAdmActionPerformed(evt);
            }
        });

        apellidoAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        apellidoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidoAdmActionPerformed(evt);
            }
        });

        edadAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edad:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        edadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadAdmActionPerformed(evt);
            }
        });

        telefonoAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        telefonoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoAdmActionPerformed(evt);
            }
        });

        emailAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        emailAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAdmActionPerformed(evt);
            }
        });

        cargoAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargo:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        cargoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoAdmActionPerformed(evt);
            }
        });

        departamentoAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Departamento Asignado:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N
        departamentoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoAdmActionPerformed(evt);
            }
        });

        registroAdministrativo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        registroAdministrativo.setText("REGISTRARSE");
        registroAdministrativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAdministrativoActionPerformed(evt);
            }
        });

        sexoAdm.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        sexoAdm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Femenino", "Masculino" }));
        sexoAdm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(edadAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sexoAdm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nombreAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(apellidoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(telefonoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cargoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(departamentoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(registroAdministrativo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apellidoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registroAdministrativo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(1316, 1660, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(545, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEstActionPerformed

    private void telefonoEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoEstActionPerformed

    private void apellidoEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoEstActionPerformed

    private void edadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadEstActionPerformed

    private void direccionEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionEstActionPerformed

    private void emailEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailEstActionPerformed

    private void facultadEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facultadEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_facultadEstActionPerformed

    private void carreraEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreraEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carreraEstActionPerformed

    private void semestreEstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semestreEstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semestreEstActionPerformed

    private void nombreProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreProfActionPerformed

    private void edadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadProfActionPerformed

    private void direccionProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionProfActionPerformed

    private void telefonoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoProfActionPerformed

    private void emailProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailProfActionPerformed

    private void contratoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contratoProfActionPerformed

    private void profesionProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesionProfActionPerformed

    private void apellidoProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoProfActionPerformed

    private void nombreAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreAdmActionPerformed

    private void apellidoAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidoAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidoAdmActionPerformed

    private void edadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edadAdmActionPerformed

    private void telefonoAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoAdmActionPerformed

    private void emailAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailAdmActionPerformed

    private void cargoAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoAdmActionPerformed

    private void departamentoAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoAdmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoAdmActionPerformed

    
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem() == "ESTUDIANTE"){
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
        }
        else if(jComboBox1.getSelectedItem() == "PROFESOR"){
            jPanel2.setVisible(false);
            jPanel3.setVisible(true);
            jPanel4.setVisible(false);
        }
        else if(jComboBox1.getSelectedItem() == "ADMINISTRATIVO"){
            jPanel2.setVisible(false);
            jPanel3.setVisible(false);
            jPanel4.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ESTUDIANTE(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ESTUDIANTE
        
    }//GEN-LAST:event_ESTUDIANTE

    private void PROFESOR(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_PROFESOR
        
    }//GEN-LAST:event_PROFESOR

    private void ADMINISTRATIVO(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_ADMINISTRATIVO
        
    }//GEN-LAST:event_ADMINISTRATIVO

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentShown

    private void registroEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroEstudianteActionPerformed
        String nombreE = nombreEst.getText();
        String apellidoE = apellidoEst.getText();
        String telefonoE = telefonoEst.getText();
        String emailE = emailEst.getText();
        String edadE = edadEst.getText();
        String facultadE = facultadEst.getText();
        String sexoE = (String) sexoEst.getSelectedItem();
        String carreraE = carreraEst.getText();
        String direccionE = direccionEst.getText();
        String semestreE = semestreEst.getText();
        Estudiante objRegEst = new Estudiante(nombreE, apellidoE, telefonoE, emailE, edadE,
        facultadE, sexoE, carreraE, direccionE, semestreE);
        objRegEst.setNombre(nombreE);
        objRegEst.setApellido(apellidoE);
        objRegEst.setTelefono(telefonoE);
        objRegEst.setEmail(emailE);
        objRegEst.setEdad(edadE);
        objRegEst.setFacultad(facultadE);
        objRegEst.setSexo(sexoE);
        objRegEst.setCarrera(carreraE);
        objRegEst.setDireccion(direccionE);
        objRegEst.setSemestre(semestreE);
        
        JOptionPane.showMessageDialog(null, "Usuario creado exitosamente"+
                        " con los siguientes datos:\n"+objRegEst.toString());
        
       // Limpiar texto 
       nombreEst.setText(null);
       apellidoEst.setText(null);
       telefonoEst.setText(null);
       emailEst.setText(null);
       edadEst.setText(null);
       facultadEst.setText(null);
       carreraEst.setText(null);
       direccionEst.setText(null);
       semestreEst.setText(null);
       
    }//GEN-LAST:event_registroEstudianteActionPerformed

    private void registroProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroProfesoresActionPerformed
        String nombreP = nombreProf.getText();
        String apellidoP = apellidoProf.getText();
        String telefonoP = telefonoProf.getText();
        String emailP = emailProf.getText();
        String edadP = edadProf.getText();
        String contratoP = contratoProf.getText();
        String sexoP = (String) sexoProf.getSelectedItem();
        String profesionP = profesionProf.getText();
        String direccionP = direccionProf.getText();        
        Profesor objRegProf = new Profesor(nombreP, apellidoP, telefonoP,
                emailP, edadP, contratoP, sexoP, profesionP, direccionP);
        objRegProf.setNombre(nombreP);
        objRegProf.setApellido(apellidoP);
        objRegProf.setTelefono(telefonoP);
        objRegProf.setEmail(emailP);
        objRegProf.setEdad(edadP);
        objRegProf.setTipoContrato(contratoP);
        objRegProf.setSexo(sexoP);
        objRegProf.setProfesion(profesionP);
        objRegProf.setDireccion(direccionP);
        JOptionPane.showMessageDialog(null, "Usuario creado exitosamente"+
                "con los siguientes datos:\n" + objRegProf.toString());
        
        // Limpiar texto 
       nombreProf.setText(null);
       apellidoProf.setText(null);
       telefonoProf.setText(null);
       emailProf.setText(null);
       edadProf.setText(null);
       profesionProf.setText(null);
       contratoProf.setText(null);
       direccionProf.setText(null);
       
        
    }//GEN-LAST:event_registroProfesoresActionPerformed

    private void registroAdministrativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAdministrativoActionPerformed
        String nombreAdmin = nombreAdm.getText();
        String apellidoAdmin = apellidoAdm.getText();
        String edadAdmin = edadAdm.getText();
        String sexoAdmin = (String) sexoAdm.getSelectedItem();
        String telefonoAdmin = telefonoAdm.getText();
        String emailAdmin = emailAdm.getText();
        String cargoAdmin = cargoAdm.getText();
        String departamentoAdmin = departamentoAdm.getText();
        
        Administrativo objAdmin = new Administrativo(nombreAdmin, apellidoAdmin, edadAdmin,
            sexoAdmin, telefonoAdmin, emailAdmin, cargoAdmin, departamentoAdmin);
        
        objAdmin.setNombre(nombreAdmin);
        objAdmin.setApellido(apellidoAdmin);
        objAdmin.setEdad(edadAdmin);
        objAdmin.setSexo(sexoAdmin);
        objAdmin.setTelefono(telefonoAdmin);
        objAdmin.setEmail(emailAdmin);
        objAdmin.setCargo(cargoAdmin);
        objAdmin.setDepartamentoAsignado(departamentoAdmin);
        
        JOptionPane.showMessageDialog(null, "Usuario creado exitosamente"+
                "con los siguientes datos:\n" + objAdmin.toString());
        
       nombreAdm.setText(null);
       apellidoAdm.setText(null);
       telefonoAdm.setText(null);
       emailAdm.setText(null);
       edadAdm.setText(null);
       cargoAdm.setText(null);
       departamentoAdm.setText(null);
               
    }//GEN-LAST:event_registroAdministrativoActionPerformed

    /**
    // * @param args the command line arguments
     */
    public static void main(String args[]) {
            
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidoAdm;
    private javax.swing.JTextField apellidoEst;
    private javax.swing.JTextField apellidoProf;
    private javax.swing.JTextField cargoAdm;
    private javax.swing.JTextField carreraEst;
    private javax.swing.JTextField contratoProf;
    private javax.swing.JTextField departamentoAdm;
    private javax.swing.JTextField direccionEst;
    private javax.swing.JTextField direccionProf;
    private javax.swing.JTextField edadAdm;
    private javax.swing.JTextField edadEst;
    private javax.swing.JTextField edadProf;
    private javax.swing.JTextField emailAdm;
    private javax.swing.JTextField emailEst;
    private javax.swing.JTextField emailProf;
    private javax.swing.JTextField facultadEst;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nombreAdm;
    private javax.swing.JTextField nombreEst;
    private javax.swing.JTextField nombreProf;
    private javax.swing.JTextField profesionProf;
    private javax.swing.JButton registroAdministrativo;
    private javax.swing.JButton registroEstudiante;
    private javax.swing.JButton registroProfesores;
    private javax.swing.JTextField semestreEst;
    private javax.swing.JComboBox<String> sexoAdm;
    private javax.swing.JComboBox<String> sexoEst;
    private javax.swing.JComboBox<String> sexoProf;
    private javax.swing.JTextField telefonoAdm;
    private javax.swing.JTextField telefonoEst;
    private javax.swing.JTextField telefonoProf;
    // End of variables declaration//GEN-END:variables

    private void ocultarPaneles() {
        if (jComboBox1.getSelectedItem() == "ESTUDIANTE"){
            jPanel2.setVisible(true);
            jPanel3.setVisible(false);
            jPanel4.setVisible(false);
        }
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
    }
}
